import type { MatcherCard } from '@/types/matcher';

export const MOCK_CARDS: MatcherCard[] = [
  {
    book: {
      id: 1,
      ownerId: 10,
      isbn: '978-0-06-112008-4',
      titulo: 'Cien años de soledad',
      autor: 'Gabriel García Márquez',
      editorial: 'Editorial Sudamericana',
      numPaginas: 471,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: null,
      status: 'PUBLISHED',
      createdAt: '2025-01-15T10:00:00Z',
      updatedAt: '2025-01-15T10:00:00Z',
      genres: [{ id: 1, name: 'Realismo mágico' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 1, bookId: 1, url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 10,
      username: 'maria_lectora',
      nombre: 'María García',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=maria',
      plan: 'FREE',
      ratingMean: 4.5,
      finishedExchanges: 12,
      xpTotal: 2400,
    },
    distanceKm: 1.2,
    score: 92,
  },
  {
    book: {
      id: 2,
      ownerId: 11,
      isbn: '978-84-204-8311-3',
      titulo: '1984',
      autor: 'George Orwell',
      editorial: 'Debolsillo',
      numPaginas: 326,
      cover: 'HARDCOVER',
      condition: 'LIKE_NEW',
      observaciones: null,
      status: 'PUBLISHED',
      createdAt: '2025-02-01T08:00:00Z',
      updatedAt: '2025-02-01T08:00:00Z',
      genres: [{ id: 2, name: 'Distopía' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 2, bookId: 2, url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 11,
      username: 'carlos_books',
      nombre: 'Carlos López',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=carlos',
      plan: 'PREMIUM',
      ratingMean: 4.8,
      finishedExchanges: 25,
      xpTotal: 5100,
    },
    distanceKm: 0.8,
    score: 88,
  },
  {
    book: {
      id: 3,
      ownerId: 12,
      isbn: '978-0-7432-7356-5',
      titulo: 'El Principito',
      autor: 'Antoine de Saint-Exupéry',
      editorial: 'Salamandra',
      numPaginas: 96,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: null,
      status: 'PUBLISHED',
      createdAt: '2025-01-20T12:00:00Z',
      updatedAt: '2025-01-20T12:00:00Z',
      genres: [{ id: 3, name: 'Fábula' }],
      languages: [{ id: 2, language: 'Francés' }, { id: 1, language: 'Español' }],
      photos: [
        { id: 3, bookId: 3, url: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 12,
      username: 'ana_reads',
      nombre: 'Ana Martínez',
      fotoPerfilUrl: null,
      plan: 'FREE',
      ratingMean: 3.9,
      finishedExchanges: 5,
      xpTotal: 800,
    },
    distanceKm: 3.5,
    score: 75,
  },
];
