import type { MatcherCard } from '@/types/matcher';

export const MOCK_CARDS: MatcherCard[] = [
  {
    book: {
      id: 1,
      ownerId: 10,
      isbn: '978-0-06-112008-4',
      titulo: 'Cien años de soledad',
      autor: 'Gabriel García Márquez',
      editorial: 'Editorial Sudamericana',
      numPaginas: 471,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: 'Buen estado general, leves marcas en la cubierta.',
      status: 'PUBLISHED',
      createdAt: '2025-01-15T10:00:00Z',
      updatedAt: '2025-01-15T10:00:00Z',
      genres: [{ id: 1, name: 'Realismo mágico' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 1, bookId: 1, url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 10,
      username: 'maria_lectora',
      nombre: 'María García',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=maria',
      plan: 'FREE',
      ratingMean: 4.5,
      finishedExchanges: 12,
      xpTotal: 2400,
    },
    distanceKm: 1.2,
    score: 92,
  },
  {
    book: {
      id: 2,
      ownerId: 11,
      isbn: '978-84-204-8311-3',
      titulo: '1984',
      autor: 'George Orwell',
      editorial: 'Debolsillo',
      numPaginas: 326,
      cover: 'HARDCOVER',
      condition: 'LIKE_NEW',
      observaciones: 'Como nuevo, apenas abierto. Sin subrayados.',
      status: 'PUBLISHED',
      createdAt: '2025-02-01T08:00:00Z',
      updatedAt: '2025-02-01T08:00:00Z',
      genres: [{ id: 2, name: 'Distopía' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 2, bookId: 2, url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 11,
      username: 'carlos_books',
      nombre: 'Carlos López',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=carlos',
      plan: 'PREMIUM',
      ratingMean: 4.8,
      finishedExchanges: 25,
      xpTotal: 5100,
    },
    distanceKm: 0.8,
    score: 88,
  },
  {
    book: {
      id: 3,
      ownerId: 12,
      isbn: '978-0-7432-7356-5',
      titulo: 'El Principito',
      autor: 'Antoine de Saint-Exupéry',
      editorial: 'Salamandra',
      numPaginas: 96,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Algunas páginas con señales de uso; encuadernación correcta.',
      status: 'PUBLISHED',
      createdAt: '2025-01-20T12:00:00Z',
      updatedAt: '2025-01-20T12:00:00Z',
      genres: [{ id: 3, name: 'Fábula' }],
      languages: [{ id: 2, language: 'Francés' }, { id: 1, language: 'Español' }],
      photos: [
        { id: 3, bookId: 3, url: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 12,
      username: 'ana_reads',
      nombre: 'Ana Martínez',
      fotoPerfilUrl: null,
      plan: 'FREE',
      ratingMean: 3.9,
      finishedExchanges: 5,
      xpTotal: 800,
    },
    distanceKm: 3.5,
    score: 75,
  },
  {
    book: {
      id: 4,
      ownerId: 13,
      isbn: '978-84-376-0494-7',
      titulo: 'La sombra del viento',
      autor: 'Carlos Ruiz Zafón',
      editorial: 'Planeta',
      numPaginas: 576,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: 'Muy cuidado, ligera curvatura en el lomo por lectura.',
      status: 'PUBLISHED',
      createdAt: '2025-02-05T09:00:00Z',
      updatedAt: '2025-02-05T09:00:00Z',
      genres: [{ id: 4, name: 'Misterio' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 4, bookId: 4, url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 13,
      username: 'bookhunter',
      nombre: 'Luis Pérez',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=luis',
      plan: 'FREE',
      ratingMean: 4.2,
      finishedExchanges: 18,
      xpTotal: 3200,
    },
    distanceKm: 2.1,
    score: 85,
  },
  {
    book: {
      id: 5,
      ownerId: 14,
      isbn: '978-84-08-23110-7',
      titulo: 'Sapiens',
      autor: 'Yuval Noah Harari',
      editorial: 'Debate',
      numPaginas: 496,
      cover: 'HARDCOVER',
      condition: 'LIKE_NEW',
      observaciones: 'Edición tapa dura, sin marcas; guardado en estantería.',
      status: 'PUBLISHED',
      createdAt: '2025-02-10T11:00:00Z',
      updatedAt: '2025-02-10T11:00:00Z',
      genres: [{ id: 5, name: 'Ensayo' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 5, bookId: 5, url: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 14,
      username: 'history_nerd',
      nombre: 'Claudia Torres',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=claudia',
      plan: 'PREMIUM',
      ratingMean: 4.9,
      finishedExchanges: 40,
      xpTotal: 8900,
    },
    distanceKm: 4.7,
    score: 95,
  },
  {
    book: {
      id: 6,
      ownerId: 15,
      isbn: '978-84-663-2791-5',
      titulo: 'El nombre del viento',
      autor: 'Patrick Rothfuss',
      editorial: 'Plaza & Janés',
      numPaginas: 880,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Señales normales de uso; esquinas algo dobladas.',
      status: 'PUBLISHED',
      createdAt: '2025-02-12T14:00:00Z',
      updatedAt: '2025-02-12T14:00:00Z',
      genres: [{ id: 6, name: 'Fantasía' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 6, bookId: 6, url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 15,
      username: 'fantasy_fan',
      nombre: 'Javier Ruiz',
      fotoPerfilUrl: null,
      plan: 'FREE',
      ratingMean: 4.6,
      finishedExchanges: 14,
      xpTotal: 2700,
    },
    distanceKm: 6.3,
    score: 89,
  },
  {
    book: {
      id: 7,
      ownerId: 16,
      isbn: '978-84-670-5954-9',
      titulo: 'Los juegos del hambre',
      autor: 'Suzanne Collins',
      editorial: 'Molino',
      numPaginas: 400,
      cover: 'HARDCOVER',
      condition: 'VERY_GOOD',
      observaciones: 'Tapa dura con rozaduras mínimas; interior perfecto.',
      status: 'PUBLISHED',
      createdAt: '2025-02-14T10:30:00Z',
      updatedAt: '2025-02-14T10:30:00Z',
      genres: [{ id: 2, name: 'Distopía' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 7, bookId: 7, url: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 16,
      username: 'katniss_reader',
      nombre: 'Laura Sánchez',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=laura',
      plan: 'FREE',
      ratingMean: 4.1,
      finishedExchanges: 9,
      xpTotal: 1500,
    },
    distanceKm: 2.9,
    score: 82,
  },
  {
    book: {
      id: 8,
      ownerId: 17,
      isbn: '978-84-450-7577-3',
      titulo: 'El código Da Vinci',
      autor: 'Dan Brown',
      editorial: 'Umbriel',
      numPaginas: 592,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Algunas páginas ligeramente amarillentas por el tiempo.',
      status: 'PUBLISHED',
      createdAt: '2025-02-15T16:00:00Z',
      updatedAt: '2025-02-15T16:00:00Z',
      genres: [{ id: 4, name: 'Misterio' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 8, bookId: 8, url: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 17,
      username: 'thriller_addict',
      nombre: 'Miguel Castro',
      fotoPerfilUrl: null,
      plan: 'PREMIUM',
      ratingMean: 4.3,
      finishedExchanges: 21,
      xpTotal: 4100,
    },
    distanceKm: 5.4,
    score: 80,
  },
  {
    book: {
      id: 9,
      ownerId: 18,
      isbn: '978-84-08-19326-9',
      titulo: 'La chica del tren',
      autor: 'Paula Hawkins',
      editorial: 'Planeta',
      numPaginas: 496,
      cover: 'PAPERBACK',
      condition: 'LIKE_NEW',
      observaciones: 'Sin marcas ni dobleces; leído una sola vez.',
      status: 'PUBLISHED',
      createdAt: '2025-02-16T18:00:00Z',
      updatedAt: '2025-02-16T18:00:00Z',
      genres: [{ id: 4, name: 'Thriller' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 9, bookId: 9, url: 'https://images.unsplash.com/photo-1496104679561-38c2b8c8f54b?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 18,
      username: 'mystery_lover',
      nombre: 'Sofía Romero',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=sofia',
      plan: 'FREE',
      ratingMean: 4.0,
      finishedExchanges: 11,
      xpTotal: 2000,
    },
    distanceKm: 1.7,
    score: 87,
  },
  {
    book: {
      id: 10,
      ownerId: 19,
      isbn: '978-84-376-0495-4',
      titulo: 'It',
      autor: 'Stephen King',
      editorial: 'Plaza & Janés',
      numPaginas: 1504,
      cover: 'HARDCOVER',
      condition: 'VERY_GOOD',
      observaciones: 'Tapa dura con leves marcas en la sobrecubierta.',
      status: 'PUBLISHED',
      createdAt: '2025-02-18T09:00:00Z',
      updatedAt: '2025-02-18T09:00:00Z',
      genres: [{ id: 7, name: 'Terror' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 10, bookId: 10, url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 19,
      username: 'horror_fan',
      nombre: 'Diego Navarro',
      fotoPerfilUrl: null,
      plan: 'PREMIUM',
      ratingMean: 4.7,
      finishedExchanges: 30,
      xpTotal: 6000,
    },
    distanceKm: 7.2,
    score: 90,
  },

  // --- NUEVOS (11 -> 30) ---

  {
    book: {
      id: 11,
      ownerId: 20,
      isbn: '978-84-663-1780-0',
      titulo: 'Dune',
      autor: 'Frank Herbert',
      editorial: 'Nova',
      numPaginas: 784,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: 'Portada con pequeño roce; páginas en muy buen estado.',
      status: 'PUBLISHED',
      createdAt: '2025-02-19T10:00:00Z',
      updatedAt: '2025-02-19T10:00:00Z',
      genres: [{ id: 8, name: 'Ciencia ficción' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 11, bookId: 11, url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 20,
      username: 'scifi_pablo',
      nombre: 'Pablo Ortega',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=pablo',
      plan: 'FREE',
      ratingMean: 4.4,
      finishedExchanges: 16,
      xpTotal: 3100,
    },
    distanceKm: 3.1,
    score: 86,
  },
  {
    book: {
      id: 12,
      ownerId: 21,
      isbn: '978-84-9062-695-8',
      titulo: 'El poder del ahora',
      autor: 'Eckhart Tolle',
      editorial: 'Gaia',
      numPaginas: 256,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Subrayados en algunos capítulos',
      status: 'PUBLISHED',
      createdAt: '2025-02-20T18:20:00Z',
      updatedAt: '2025-02-20T18:20:00Z',
      genres: [{ id: 5, name: 'Ensayo' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 12, bookId: 12, url: 'https://images.unsplash.com/photo-1455885666463-8bea1d29c34f?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 21,
      username: 'mindful_sara',
      nombre: 'Sara Vidal',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=sara',
      plan: 'FREE',
      ratingMean: 4.1,
      finishedExchanges: 7,
      xpTotal: 1200,
    },
    distanceKm: 0.9,
    score: 78,
  },
  {
    book: {
      id: 13,
      ownerId: 22,
      isbn: '978-84-663-3525-5',
      titulo: 'El Hobbit',
      autor: 'J. R. R. Tolkien',
      editorial: 'Minotauro',
      numPaginas: 320,
      cover: 'HARDCOVER',
      condition: 'LIKE_NEW',
      observaciones: 'Edición muy cuidada, sin golpes ni manchas.',
      status: 'PUBLISHED',
      createdAt: '2025-02-21T09:15:00Z',
      updatedAt: '2025-02-21T09:15:00Z',
      genres: [{ id: 6, name: 'Fantasía' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 13, bookId: 13, url: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 22,
      username: 'tolkienista',
      nombre: 'Álvaro Núñez',
      fotoPerfilUrl: null,
      plan: 'PREMIUM',
      ratingMean: 4.6,
      finishedExchanges: 33,
      xpTotal: 7200,
    },
    distanceKm: 8.4,
    score: 91,
  },
  {
    book: {
      id: 14,
      ownerId: 23,
      isbn: '978-84-322-1985-6',
      titulo: 'Orgullo y prejuicio',
      autor: 'Jane Austen',
      editorial: 'Austral',
      numPaginas: 384,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: 'Leve desgaste en bordes; páginas limpias, sin anotaciones.',
      status: 'PUBLISHED',
      createdAt: '2025-02-22T12:00:00Z',
      updatedAt: '2025-02-22T12:00:00Z',
      genres: [{ id: 9, name: 'Clásico' }],
      languages: [{ id: 1, language: 'Español' }, { id: 3, language: 'Inglés' }],
      photos: [
        { id: 14, bookId: 14, url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 23,
      username: 'classic_nora',
      nombre: 'Nora Delgado',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=nora',
      plan: 'FREE',
      ratingMean: 4.0,
      finishedExchanges: 10,
      xpTotal: 1900,
    },
    distanceKm: 2.6,
    score: 84,
  },
  {
    book: {
      id: 15,
      ownerId: 24,
      isbn: '978-84-339-8040-9',
      titulo: 'El alquimista',
      autor: 'Paulo Coelho',
      editorial: 'Planeta',
      numPaginas: 192,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Cubierta con pequeñas arrugas; interior en buen estado.',
      status: 'PUBLISHED',
      createdAt: '2025-02-23T17:40:00Z',
      updatedAt: '2025-02-23T17:40:00Z',
      genres: [{ id: 10, name: 'Narrativa' }],
      languages: [{ id: 1, language: 'Español' }, { id: 4, language: 'Portugués' }],
      photos: [
        { id: 15, bookId: 15, url: 'https://images.unsplash.com/photo-1526243741027-444d633d7365?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 24,
      username: 'viajera_lucia',
      nombre: 'Lucía Herrera',
      fotoPerfilUrl: null,
      plan: 'FREE',
      ratingMean: 3.8,
      finishedExchanges: 6,
      xpTotal: 950,
    },
    distanceKm: 4.2,
    score: 73,
  },
  {
    book: {
      id: 16,
      ownerId: 25,
      isbn: '978-84-253-5320-1',
      titulo: 'Fahrenheit 451',
      autor: 'Ray Bradbury',
      editorial: 'Debolsillo',
      numPaginas: 256,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: 'Sin subrayados; lomo ligeramente marcado por lectura.',
      status: 'PUBLISHED',
      createdAt: '2025-02-24T08:10:00Z',
      updatedAt: '2025-02-24T08:10:00Z',
      genres: [{ id: 2, name: 'Distopía' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 16, bookId: 16, url: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 25,
      username: 'paperless',
      nombre: 'Iván Molina',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=ivan',
      plan: 'PREMIUM',
      ratingMean: 4.5,
      finishedExchanges: 28,
      xpTotal: 5600,
    },
    distanceKm: 1.4,
    score: 90,
  },
  {
    book: {
      id: 17,
      ownerId: 26,
      isbn: '978-84-670-5320-2',
      titulo: 'Ready Player One',
      autor: 'Ernest Cline',
      editorial: 'Nova',
      numPaginas: 480,
      cover: 'HARDCOVER',
      condition: 'LIKE_NEW',
      observaciones: 'Tapa dura impecable; sin marcas, guardado con funda.',
      status: 'PUBLISHED',
      createdAt: '2025-02-25T20:00:00Z',
      updatedAt: '2025-02-25T20:00:00Z',
      genres: [{ id: 8, name: 'Ciencia ficción' }],
      languages: [{ id: 1, language: 'Español' }, { id: 3, language: 'Inglés' }],
      photos: [
        { id: 17, bookId: 17, url: 'https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 26,
      username: 'retro_gamer',
      nombre: 'Raúl Campos',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=raul',
      plan: 'FREE',
      ratingMean: 4.2,
      finishedExchanges: 13,
      xpTotal: 2600,
    },
    distanceKm: 9.1,
    score: 83,
  },
  {
    book: {
      id: 18,
      ownerId: 27,
      isbn: '978-84-204-8277-2',
      titulo: 'Rebelión en la granja',
      autor: 'George Orwell',
      editorial: 'Debolsillo',
      numPaginas: 144,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Portada algo gastada; páginas limpias y sin anotaciones.',
      status: 'PUBLISHED',
      createdAt: '2025-02-26T07:30:00Z',
      updatedAt: '2025-02-26T07:30:00Z',
      genres: [{ id: 9, name: 'Clásico' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 18, bookId: 18, url: 'https://images.unsplash.com/photo-1521056787327-165dc2b1a2e0?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 27,
      username: 'orwellian',
      nombre: 'Teresa Ríos',
      fotoPerfilUrl: null,
      plan: 'FREE',
      ratingMean: 4.0,
      finishedExchanges: 8,
      xpTotal: 1400,
    },
    distanceKm: 2.0,
    score: 79,
  },
  {
    book: {
      id: 19,
      ownerId: 28,
      isbn: '978-84-666-1234-8',
      titulo: 'El psicoanalista',
      autor: 'John Katzenbach',
      editorial: 'Ediciones B',
      numPaginas: 576,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: 'Leve desgaste en la portada; interior como nuevo.',
      status: 'PUBLISHED',
      createdAt: '2025-02-26T16:45:00Z',
      updatedAt: '2025-02-26T16:45:00Z',
      genres: [{ id: 4, name: 'Thriller' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 19, bookId: 19, url: 'https://images.unsplash.com/photo-1509266272358-7701da638078?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 28,
      username: 'page_turner',
      nombre: 'Héctor León',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=hector',
      plan: 'PREMIUM',
      ratingMean: 4.4,
      finishedExchanges: 22,
      xpTotal: 4300,
    },
    distanceKm: 5.9,
    score: 88,
  },
  {
    book: {
      id: 20,
      ownerId: 29,
      isbn: '978-84-270-4766-5',
      titulo: 'El guardián entre el centeno',
      autor: 'J. D. Salinger',
      editorial: 'Alianza',
      numPaginas: 224,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Lomo con marcas de uso; sin subrayados ni anotaciones.',
      status: 'PUBLISHED',
      createdAt: '2025-02-27T10:05:00Z',
      updatedAt: '2025-02-27T10:05:00Z',
      genres: [{ id: 9, name: 'Clásico' }],
      languages: [{ id: 1, language: 'Español' }, { id: 3, language: 'Inglés' }],
      photos: [
        { id: 20, bookId: 20, url: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 29,
      username: 'holden_reader',
      nombre: 'Elena Cruz',
      fotoPerfilUrl: null,
      plan: 'FREE',
      ratingMean: 3.7,
      finishedExchanges: 4,
      xpTotal: 600,
    },
    distanceKm: 0.6,
    score: 70,
  },

  {
    book: {
      id: 21,
      ownerId: 30,
      isbn: '978-84-663-2601-7',
      titulo: 'El camino de los reyes',
      autor: 'Brandon Sanderson',
      editorial: 'Nova',
      numPaginas: 1248,
      cover: 'HARDCOVER',
      condition: 'VERY_GOOD',
      observaciones: 'Volumen grande; cubierta con rozaduras mínimas.',
      status: 'PUBLISHED',
      createdAt: '2025-02-27T18:30:00Z',
      updatedAt: '2025-02-27T18:30:00Z',
      genres: [{ id: 6, name: 'Fantasía' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 21, bookId: 21, url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 30,
      username: 'stormlight',
      nombre: 'Marcos Gil',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=marcos',
      plan: 'PREMIUM',
      ratingMean: 4.8,
      finishedExchanges: 35,
      xpTotal: 7600,
    },
    distanceKm: 12.3,
    score: 94,
  },
  {
    book: {
      id: 22,
      ownerId: 31,
      isbn: '978-84-233-5392-6',
      titulo: 'La metamorfosis',
      autor: 'Franz Kafka',
      editorial: 'Destino',
      numPaginas: 128,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: 'Edición de bolsillo, muy cuidada; sin marcas.',
      status: 'PUBLISHED',
      createdAt: '2025-02-28T09:00:00Z',
      updatedAt: '2025-02-28T09:00:00Z',
      genres: [{ id: 9, name: 'Clásico' }],
      languages: [{ id: 1, language: 'Español' }, { id: 5, language: 'Alemán' }],
      photos: [
        { id: 22, bookId: 22, url: 'https://images.unsplash.com/photo-1455885666463-8bea1d29c34f?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 31,
      username: 'kafka_k',
      nombre: 'Noelia Martín',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=noelia',
      plan: 'FREE',
      ratingMean: 4.1,
      finishedExchanges: 15,
      xpTotal: 2900,
    },
    distanceKm: 6.8,
    score: 85,
  },
  {
    book: {
      id: 23,
      ownerId: 32,
      isbn: '978-84-339-7802-4',
      titulo: 'El juego de Ender',
      autor: 'Orson Scott Card',
      editorial: 'Ediciones B',
      numPaginas: 352,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Ligeras marcas en la portada; páginas en buen estado.',
      status: 'PUBLISHED',
      createdAt: '2025-02-28T12:45:00Z',
      updatedAt: '2025-02-28T12:45:00Z',
      genres: [{ id: 8, name: 'Ciencia ficción' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 23, bookId: 23, url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 32,
      username: 'ender_fleet',
      nombre: 'Guillermo Vega',
      fotoPerfilUrl: null,
      plan: 'FREE',
      ratingMean: 4.3,
      finishedExchanges: 12,
      xpTotal: 2300,
    },
    distanceKm: 2.8,
    score: 84,
  },
  {
    book: {
      id: 24,
      ownerId: 33,
      isbn: '978-84-666-6789-0',
      titulo: 'Tokio Blues (Norwegian Wood)',
      autor: 'Haruki Murakami',
      editorial: 'Tusquets',
      numPaginas: 384,
      cover: 'PAPERBACK',
      condition: 'LIKE_NEW',
      observaciones: 'Leído una vez; como nuevo, sin marcas.',
      status: 'PUBLISHED',
      createdAt: '2025-03-01T09:20:00Z',
      updatedAt: '2025-03-01T09:20:00Z',
      genres: [{ id: 10, name: 'Narrativa' }],
      languages: [{ id: 1, language: 'Español' }, { id: 6, language: 'Japonés' }],
      photos: [
        { id: 24, bookId: 24, url: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 33,
      username: 'murakami_m',
      nombre: 'Paula Jiménez',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=paula',
      plan: 'PREMIUM',
      ratingMean: 4.6,
      finishedExchanges: 27,
      xpTotal: 5400,
    },
    distanceKm: 11.7,
    score: 89,
  },
  {
    book: {
      id: 25,
      ownerId: 34,
      isbn: '978-84-670-5111-6',
      titulo: 'La historia interminable',
      autor: 'Michael Ende',
      editorial: 'Alfaguara',
      numPaginas: 496,
      cover: 'HARDCOVER',
      condition: 'VERY_GOOD',
      observaciones: 'Tapa dura muy bien; páginas sin manchas.',
      status: 'PUBLISHED',
      createdAt: '2025-03-01T12:00:00Z',
      updatedAt: '2025-03-01T12:00:00Z',
      genres: [{ id: 6, name: 'Fantasía' }],
      languages: [{ id: 1, language: 'Español' }, { id: 5, language: 'Alemán' }],
      photos: [
        { id: 25, bookId: 25, url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 34,
      username: 'atreyu',
      nombre: 'Sergio Campos',
      fotoPerfilUrl: null,
      plan: 'FREE',
      ratingMean: 4.2,
      finishedExchanges: 19,
      xpTotal: 3600,
    },
    distanceKm: 3.9,
    score: 86,
  },
  {
    book: {
      id: 26,
      ownerId: 35,
      isbn: '978-84-322-3921-2',
      titulo: 'Crónica de una muerte anunciada',
      autor: 'Gabriel García Márquez',
      editorial: 'Debolsillo',
      numPaginas: 144,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Bordes algo gastados; lectura cómoda, sin anotaciones.',
      status: 'PUBLISHED',
      createdAt: '2025-03-01T18:10:00Z',
      updatedAt: '2025-03-01T18:10:00Z',
      genres: [{ id: 10, name: 'Narrativa' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 26, bookId: 26, url: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 35,
      username: 'gabo_fan',
      nombre: 'Rocío Blanco',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=rocio',
      plan: 'FREE',
      ratingMean: 4.3,
      finishedExchanges: 17,
      xpTotal: 3400,
    },
    distanceKm: 1.1,
    score: 85,
  },
  {
    book: {
      id: 27,
      ownerId: 36,
      isbn: '978-84-450-7080-8',
      titulo: 'La paciente silenciosa',
      autor: 'Alex Michaelides',
      editorial: 'Alfaguara',
      numPaginas: 368,
      cover: 'PAPERBACK',
      condition: 'LIKE_NEW',
      observaciones: 'Sin dobleces; páginas limpias y encuadernación firme.',
      status: 'PUBLISHED',
      createdAt: '2025-03-02T09:00:00Z',
      updatedAt: '2025-03-02T09:00:00Z',
      genres: [{ id: 4, name: 'Thriller' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 27, bookId: 27, url: 'https://images.unsplash.com/photo-1509266272358-7701da638078?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 36,
      username: 'silent_reader',
      nombre: 'Andrea Pineda',
      fotoPerfilUrl: null,
      plan: 'PREMIUM',
      ratingMean: 4.5,
      finishedExchanges: 24,
      xpTotal: 4800,
    },
    distanceKm: 4.0,
    score: 90,
  },
  {
    book: {
      id: 28,
      ownerId: 37,
      isbn: '978-84-376-1122-8',
      titulo: 'Drácula',
      autor: 'Bram Stoker',
      editorial: 'Austral',
      numPaginas: 512,
      cover: 'HARDCOVER',
      condition: 'VERY_GOOD',
      observaciones: 'Edición clásica; tapa dura con leves roces en cantos.',
      status: 'PUBLISHED',
      createdAt: '2025-03-02T11:30:00Z',
      updatedAt: '2025-03-02T11:30:00Z',
      genres: [{ id: 7, name: 'Terror' }],
      languages: [{ id: 1, language: 'Español' }, { id: 3, language: 'Inglés' }],
      photos: [
        { id: 28, bookId: 28, url: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 37,
      username: 'gothic_pages',
      nombre: 'Adrián Serrano',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=adrian',
      plan: 'FREE',
      ratingMean: 4.1,
      finishedExchanges: 9,
      xpTotal: 1600,
    },
    distanceKm: 7.7,
    score: 84,
  },
  {
    book: {
      id: 29,
      ownerId: 38,
      isbn: '978-84-339-9999-9',
      titulo: 'Breves respuestas a las grandes preguntas',
      autor: 'Stephen Hawking',
      editorial: 'Crítica',
      numPaginas: 256,
      cover: 'PAPERBACK',
      condition: 'VERY_GOOD',
      observaciones: 'Sin subrayados; cubierta con mínima marca superficial.',
      status: 'PUBLISHED',
      createdAt: '2025-03-02T15:00:00Z',
      updatedAt: '2025-03-02T15:00:00Z',
      genres: [{ id: 5, name: 'Ensayo' }],
      languages: [{ id: 1, language: 'Español' }],
      photos: [
        { id: 29, bookId: 29, url: 'https://images.unsplash.com/photo-1528207776546-a1c2e315a42f?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 38,
      username: 'cosmos_mate',
      nombre: 'Mateo Díaz',
      fotoPerfilUrl: null,
      plan: 'PREMIUM',
      ratingMean: 4.7,
      finishedExchanges: 29,
      xpTotal: 5900,
    },
    distanceKm: 10.2,
    score: 88,
  },
  {
    book: {
      id: 30,
      ownerId: 39,
      isbn: '978-84-9808-000-0',
      titulo: 'El arte de la guerra',
      autor: 'Sun Tzu',
      editorial: 'Alianza',
      numPaginas: 192,
      cover: 'PAPERBACK',
      condition: 'GOOD',
      observaciones: 'Edición pequeña; algunas páginas con leve ondulación.',
      status: 'PUBLISHED',
      createdAt: '2025-03-02T19:10:00Z',
      updatedAt: '2025-03-02T19:10:00Z',
      genres: [{ id: 5, name: 'Ensayo' }],
      languages: [{ id: 1, language: 'Español' }, { id: 7, language: 'Chino' }],
      photos: [
        { id: 30, bookId: 30, url: 'https://images.unsplash.com/photo-1455885666463-8bea1d29c34f?w=600&h=900&fit=crop', orden: 0 },
      ],
    },
    owner: {
      id: 39,
      username: 'strategy_ale',
      nombre: 'Alejandro Cano',
      fotoPerfilUrl: 'https://i.pravatar.cc/150?u=alejandro',
      plan: 'FREE',
      ratingMean: 4.0,
      finishedExchanges: 8,
      xpTotal: 1450,
    },
    distanceKm: 2.3,
    score: 77,
  },
];